Vagrant.configure("2") do |config|

  config.env.enable
  config.vm.box = "aws"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  config.vm.synced_folder ENV['SYNC_LOCAL'], ENV['SYNC_REMOTE']

  config.vm.provider :aws do |aws, override|

    aws.access_key_id = ENV['ACCESS_KEY_ID']
    aws.secret_access_key = ENV['SECRET_ACCESS_KEY']
    aws.keypair_name = ENV['KEYPAIR_NAME']

    aws.ami = ENV['AMI']
    aws.region = ENV['REGION']
    aws.instance_type = ENV['INSTANCE_TYPE']
    aws.security_groups = ENV['SECURITY_GROUPS']
    aws.subnet_id = ENV['SUBNET_ID']
    aws.associate_public_ip = ENV['ASSOCIATE_PUBLIC_IP']

    aws.user_data = File.read(ENV['USER_DATA_FILE'])

    aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => ENV['VOLUMESIZE'] }]
    aws.tags = {
      'Name' => ENV['FQDN'],
      'CreatedBy' => 'Vagrant'
    }

    override.ssh.username = ENV['SSH_USERNAME']
    override.ssh.password = ENV['SSH_PASSWORD']
    override.ssh.private_key_path = ENV['SSH_PRIVATE_KEY_PATH']
  end
end
