Vagrant.configure("2") do |config|

  config.env.enable
  config.vm.hostname = ENV['FQDN']
  config.vm.synced_folder "#{ENV['SYNC_LOCAL']}", "#{ENV['SYNC_REMOTE']}", type: "rsync"

  begin
    config.vm.provision :shell, :path => "#{ENV['BOOTSTRAP_SCRIPT']}", :args => "#{ENV['LSBDISTCODENAME']} #{ENV['FQDN']}"
  rescue
  end

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['ACCESS_KEY_ID']
    aws.secret_access_key = ENV['SECRET_ACCESS_KEY']
    aws.keypair_name = ENV['KEYPAIR_NAME']

    aws.ami = ENV['AMI']
    aws.region = ENV['REGION']
    aws.instance_type = ENV['INSTANCE_TYPE']
    aws.security_groups = ENV['SECURITY_GROUPS'].split(",")
    aws.subnet_id = ENV['SUBNET_ID']
    aws.associate_public_ip = ENV['ASSOCIATE_PUBLIC_IP']

    # If the bootstrap script can't be copied over due to rsync issues, try to 
    # pass it as EC2 user data.
    begin
      aws.user_data = File.read(ENV['USER_DATA_FILE'])
    rescue
    end

    aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => ENV['VOLUMESIZE'] }]
    aws.tags = {
      'Name' => ENV['FQDN'],
      'CreatedBy' => 'Vagrant'
    }

    override.ssh.username = ENV['SSH_USERNAME']
    override.ssh.password = ENV['SSH_PASSWORD']
    override.ssh.private_key_path = ENV['SSH_PRIVATE_KEY_PATH']

    override.vm.box = "aws"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  end
end
