Vagrant.configure("2") do |config|

  # Generic settings
  config.env.enable
  config.vm.hostname = ENV['FQDN']
  config.vm.synced_folder "#{ENV['SYNC_LOCAL']}", "#{ENV['SYNC_REMOTE']}", create: true, disabled: ENV['SYNC_DISABLED'] 

  # AWS provider
  config.vm.provider :aws do |aws, override|

    aws.access_key_id = ENV['ACCESS_KEY_ID']
    aws.secret_access_key = ENV['SECRET_ACCESS_KEY']
    aws.keypair_name = ENV['KEYPAIR_NAME']

    aws.ami = ENV['AMI']
    aws.region = ENV['REGION']
    aws.instance_type = ENV['INSTANCE_TYPE']
    aws.security_groups = ENV['SECURITY_GROUPS'].split(",")
    aws.subnet_id = ENV['SUBNET_ID']
    aws.associate_public_ip = ENV['ASSOCIATE_PUBLIC_IP']

    aws.user_data = File.read(ENV['USER_DATA_FILE'])

    aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => ENV['VOLUMESIZE'] }]
    aws.tags = {
      'Name' => ENV['FQDN'],
      'CreatedBy' => 'Vagrant'
    }

    override.ssh.username = ENV['SSH_USERNAME']
    override.ssh.password = ENV['SSH_PASSWORD']
    override.ssh.private_key_path = ENV['SSH_PRIVATE_KEY_PATH']

    override.vm.box = "aws"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  end

  # Libvirt provider
  config.vm.provider :libvirt do |libvirt, override|

    libvirt.host = ENV['HOST']
    libvirt.connect_via_ssh = ENV['CONNECT_VIA_SSH']
    libvirt.username = ENV['USERNAME']
    libvirt.password = ENV['PASSWORD']
    libvirt.id_ssh_key_file = ENV['ID_SSH_KEY_FILE']
    memory = ENV['MEMORY']
    cpus = ENV['CPUS']
    graphics_type = ENV['GRAPHICS_TYPE']
    graphics_ip = ENV['GRAPHICS_IP']

    override.vm.box = ENV['BOX']
    override.vm.box_url = ENV['BOX_URL']
  end

end
